// here we passed the arguments is being overwritten by reference and the reference is being overwritten inside the called function

$ cat test1.py 
#!/usr/bin/python

#Initialize a function

def function_name(myList):
	"The changes a passed list into this function..."
	#Local Variable
	myList=[1,2,3]
	print('Values inside the function is:', myList)
	return

#Calling the function
#Global Variable
myList=[33,44,555]
function_name(myList)
print("Values outside a function: ",myList)

O/P:

$ ./test1.py 
('Values inside the function is:', [1, 2, 3])
('Values outside a function: ', [33, 44, 555])
